№7
SELECT C.COUNTRY,
       SUM(S.QUANTITY_SOLD)
FROM CUSTOMERS C
JOIN SALES S ON C.CUST_ID = S.CUST_ID
JOIN PRODUCTS P ON S.PROD_ID = P.PROD_ID
WHERE P.PROD_CATEGORY = 'Men'
GROUP BY C.COUNTRY
HAVING SUM(S.QUANTITY_SOLD) > (
  SELECT AVG(Total)
  FROM (SELECT SUM(S2.QUANTITY_SOLD) AS Total
    FROM CUSTOMERS C2
    JOIN SALES S2 ON C2.CUST_ID = S2.CUST_ID
    JOIN PRODUCTS P2 ON S2.PROD_ID = P2.PROD_ID
    WHERE P2.PROD_CATEGORY = 'Men'
    GROUP BY C2.COUNTRY
  )
)
ORDER BY C.COUNTRY;

№8
WITH Gender_Stats AS (
  SELECT 
    COUNTRY AS Country,
    SUM(CASE WHEN CUST_GENDER = 'M' THEN 1 ELSE 0 END) AS Men_Count,
    SUM(CASE WHEN CUST_GENDER = 'F' THEN 1 ELSE 0 END) AS Women_Count,
    COUNT(*) AS Total
  FROM CUSTOMERS
  WHERE CUST_GENDER IN ('M', 'F')
  GROUP BY COUNTRY
)
SELECT 
  Country AS "Страна",
  ROUND(100 * Men_Count / Total, 2) AS "% мужчин",
  ROUND(100 * Women_Count / Total, 2) AS "% женщин"
FROM Gender_Stats
ORDER BY Country;

№9
WITH Daily_Sales AS (
  SELECT P.PROD_NAME, S.TIME_ID , SUM(S.QUANTITY_SOLD) AS Total_Qty
  FROM SALES S
  JOIN PRODUCTS P ON S.PROD_ID = P.PROD_ID
  GROUP BY P.PROD_NAME, S.TIME_ID 
)
SELECT PROD_NAME,
  TO_CHAR(Total_Qty) || ' шт. / ' || TO_CHAR(TIME_ID , 'YYYY-MM-DD') AS "Макс покуп/день"
FROM Daily_Sales ds
WHERE Total_Qty = (SELECT MAX(Total_Qty)
  FROM Daily_Sales
  WHERE PROD_NAME = ds.PROD_NAME
)
ORDER BY Total_Qty DESC
FETCH FIRST 20 ROWS ONLY;

№10
SELECT 
  MAX(Daily_Total) AS "Макс за день", PROD_CATEGORY
FROM (
  SELECT PROD_CATEGORY, S.TIME_ID , SUM(S.QUANTITY_SOLD) AS Daily_Total
  FROM SALES S
  JOIN PRODUCTS P ON S.PROD_ID = P.PROD_ID
  GROUP BY p.PROD_CATEGORY, S.TIME_ID 
)
GROUP BY PROD_CATEGORY
ORDER BY "Макс за день" DESC;

№11
CREATE TABLE SALES_NIKOTIN_NIKITA_EVSYUKOV AS
SELECT *
FROM SALES
WHERE TRUNC(TIME_ID, 'MM') = (
  SELECT TRUNC(TIME_ID, 'MM')
  FROM SALES
  GROUP BY TRUNC(TIME_ID, 'MM')
  ORDER BY SUM(amount_sold) DESC
  FETCH FIRST 1 ROW ONLY
)
ORDER BY TIME_ID;

#12
UPDATE SALES_NIKOTIN_NIKITA_EVSYUKOV
SET TIME_ID = TRUNC(TIME_ID) + DBMS_RANDOM.VALUE(0, 1);

SELECT TO_CHAR(TIME_ID, 'DD.MM.YYYY HH24:MI:SS') AS FORMATED_TIME, SALES_NIKOTIN_NIKITA_EVSYUKOV.*
FROM SALES_NIKOTIN_NIKITA_EVSYUKOV
ORDER BY TIME_ID ;

#13
SELECT TO_NUMBER(TO_CHAR(TIME_ID, 'HH24')) AS HOUR, COUNT(*)
FROM SALES_NIKOTIN_NIKITA_EVSYUKOV
GROUP BY TO_NUMBER(TO_CHAR(TIME_ID, 'HH24'))
ORDER BY HOUR;

#14
DROP TABLE SALES_NIKOTIN_NIKITA_EVSYUKOV
