№1
SELECT CUST_FIRST_NAME , CUST_LAST_NAME
FROM CUSTOMERS
WHERE COUNTRY != 'Japan' AND COUNTRY != 'Brazil' AND COUNTRY != 'Italy' AND CUST_GENDER = 'F' AND CUST_MARITAL_STATUS = 'Married' AND CUST_CREDIT_LIMIT = (SELECT MIN(CUST_CREDIT_LIMIT) FROM CUSTOMERS)
ORDER BY CUST_LAST_NAME;

№2
SELECT 'Name: ' || CUST_FIRST_NAME || ' ' || CUST_LAST_NAME || '; city: ' || CUST_CITY || '; adress: ' || CUST_STREET_ADDRESS || '; number: ' || CUST_MAIN_PHONE_NUMBER || '; email: ' || CUST_EMAIL || ';'  AS TASK
FROM CUSTOMERS
WHERE CUST_MAIN_PHONE_NUMBER LIKE '%77' AND LENGTH(CUST_STREET_ADDRESS) = (SELECT MAX(LENGTH(CUST_STREET_ADDRESS)) FROM CUSTOMERS WHERE CUST_MAIN_PHONE_NUMBER LIKE '%77');

№3 (ничего не выводит)
SELECT C.CUST_ID, C.CUST_FIRST_NAME, C.CUST_LAST_NAME, C.cust_year_of_birth
FROM customers C
JOIN sales S ON C.cust_id = S.cust_id
JOIN products P ON S.prod_id = P.prod_id
WHERE C.cust_year_of_birth > 1980 AND P.prod_subcategory IN ('Sweaters - Men', 'Sweaters - Women') AND 
P.prod_list_price = (SELECT MIN(p2.prod_list_price)
    FROM products p2
    JOIN SALES s2 ON p2.PROD_ID = s2.PROD_ID
    WHERE p2.prod_subcategory IN ('Sweaters - Men', 'Sweaters - Women')
  )
ORDER BY C.cust_id;

№4
SELECT CUST_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_GENDER, CUST_INCOME_LEVEL, COUNTRY
FROM CUSTOMERS C1
WHERE EXISTS (SELECT * FROM CUSTOMERS C WHERE C1.CUST_ID = C.CUST_ID AND 
C.CUST_GENDER = 'M'AND 
C.CUST_INCOME_LEVEL LIKE 'D%' AND 
C.CUST_MARITAL_STATUS IS NULL AND 
(C.COUNTRY = 'United States of America' OR C.COUNTRY = 'Germany'))
ORDER BY CUST_ID

№5
SELECT ROUND(AVG(P.PROD_LIST_PRICE * S.QUANTITY_SOLD),2) AS AVG, COUNTRY
FROM CUSTOMERS C
JOIN SALES S ON C.CUST_ID = S.CUST_ID
JOIN PRODUCTS P ON S.PROD_ID = P.PROD_ID
GROUP BY C.COUNTRY
ORDER BY AVG(P.PROD_LIST_PRICE * S.QUANTITY_SOLD) DESC;

№6
SELECT SUBSTR(CUST_EMAIL, INSTR(CUST_EMAIL, '@')) AS DOMEN, COUNT(CUST_EMAIL) AS DOMEN_COUNT 
FROM CUSTOMERS
GROUP BY SUBSTR(CUST_EMAIL, INSTR(CUST_EMAIL, '@'))
ORDER BY COUNT(CUST_EMAIL)  DESC;
       
№7
SELECT C.COUNTRY,
       SUM(S.QUANTITY_SOLD) AS TOTAL
FROM CUSTOMERS C
JOIN SALES S ON C.CUST_ID = S.CUST_ID
JOIN PRODUCTS P ON S.PROD_ID = P.PROD_ID
WHERE P.PROD_CATEGORY = 'Men'
GROUP BY C.COUNTRY
HAVING SUM(S.QUANTITY_SOLD) > (
  SELECT AVG(Total)
  FROM (SELECT SUM(S2.QUANTITY_SOLD) AS Total
    FROM CUSTOMERS C2
    JOIN SALES S2 ON C2.CUST_ID = S2.CUST_ID
    JOIN PRODUCTS P2 ON S2.PROD_ID = P2.PROD_ID
    WHERE P2.PROD_CATEGORY = 'Men'
    GROUP BY C2.COUNTRY
  )
)
ORDER BY C.COUNTRY;

№8
WITH Gender_Stats AS (
  SELECT 
    COUNTRY AS Country,
    SUM(CASE WHEN CUST_GENDER = 'M' THEN 1 ELSE 0 END) AS Men_Count,
    SUM(CASE WHEN CUST_GENDER = 'F' THEN 1 ELSE 0 END) AS Women_Count,
    COUNT(*) AS Total
  FROM CUSTOMERS
  WHERE CUST_GENDER IN ('M', 'F')
  GROUP BY COUNTRY
)
SELECT 
  Country AS "Страна",
  ROUND(100 * Men_Count / Total, 2) AS "% мужчин",
  ROUND(100 * Women_Count / Total, 2) AS "% женщин"
FROM Gender_Stats
ORDER BY Country;

№9
WITH Daily_Sales AS (
  SELECT P.PROD_NAME, S.TIME_ID , SUM(S.QUANTITY_SOLD) AS Total_Qty
  FROM SALES S
  JOIN PRODUCTS P ON S.PROD_ID = P.PROD_ID
  GROUP BY P.PROD_NAME, S.TIME_ID 
)
SELECT PROD_NAME,
  TO_CHAR(Total_Qty) || ' шт. / ' || TO_CHAR(TIME_ID , 'YYYY-MM-DD') AS "Макс покуп/день"
FROM Daily_Sales ds
WHERE Total_Qty = (SELECT MAX(Total_Qty)
  FROM Daily_Sales
  WHERE PROD_NAME = ds.PROD_NAME
)
ORDER BY Total_Qty DESC
FETCH FIRST 20 ROWS ONLY;

№10
SELECT 
  MAX(Daily_Total) AS "Макс за день", PROD_CATEGORY
FROM (
  SELECT PROD_CATEGORY, S.TIME_ID , SUM(S.QUANTITY_SOLD) AS Daily_Total
  FROM SALES S
  JOIN PRODUCTS P ON S.PROD_ID = P.PROD_ID
  GROUP BY p.PROD_CATEGORY, S.TIME_ID 
)
GROUP BY PROD_CATEGORY
ORDER BY "Макс за день" DESC;

№11
CREATE TABLE SALES_NIKOTIN_NIKITA_EVSYUKOV AS
SELECT *
FROM SALES
WHERE TRUNC(TIME_ID, 'MM') = (
  SELECT TRUNC(TIME_ID, 'MM')
  FROM SALES
  GROUP BY TRUNC(TIME_ID, 'MM')
  ORDER BY SUM(amount_sold) DESC
  FETCH FIRST 1 ROW ONLY
)
ORDER BY TIME_ID;

#12
UPDATE SALES_NIKOTIN_NIKITA_EVSYUKOV
SET TIME_ID = TRUNC(TIME_ID) + DBMS_RANDOM.VALUE(0, 1);

SELECT TO_CHAR(TIME_ID, 'DD.MM.YYYY HH24:MI:SS') AS FORMATED_TIME, SALES_NIKOTIN_NIKITA_EVSYUKOV.*
FROM SALES_NIKOTIN_NIKITA_EVSYUKOV
ORDER BY TIME_ID ;

#13
SELECT TO_NUMBER(TO_CHAR(TIME_ID, 'HH24')) AS HOUR, COUNT(*)
FROM SALES_NIKOTIN_NIKITA_EVSYUKOV
GROUP BY TO_NUMBER(TO_CHAR(TIME_ID, 'HH24'))
ORDER BY HOUR;

#14
DROP TABLE SALES_NIKOTIN_NIKITA_EVSYUKOV
